setup(
    name='FChatPy',
    version='0.1',
    author='Build-A-Buddha',
    python_requires='>=3',
    install_requires=['ws4py>=0.5.1'],
    packages=["fchatpy"],
    url='https://github.com/BuildABuddha/fchatpy'
)
